### ISSUE TITLE
Chatting Only With Designated Neighbors

### ISSUE THREAD

**Issue by dapacica** [empiricaly/chat#6]
I am currently using the empirica chat feature where it allows all users in the current session to chat with one another, but I am trying to implement the chat so that users can only chat with specific "neighbors" that have been set for them. Is there a configuration setting to the chat API that would allow this?

**Comment by npaton** [comment]
There is no ready-made API for this as there are many ways this might happen.

But I think there is a simple solution. You can add a `customKey` to the chat. It allows for making different chats within the same scope. Not sure how your neighbors work, but here are a couple of examples.

Maybe each group of neighbors has a group name of some sort ("group1", "group2", "group3"...), then you can just use that:

```jsx
<Chat player={player} scope={game} customKey={player.get("neighborsGroup")} />
```

Maybe neighbors change on every round and they are not assigned to a named group, and you just have a list of neighbor Player IDs. To have a chat for each unique set of neighbors, you could maybe do this (assuming you neighbors' IDs are in a `neighborIDs` key on the player):

```jsx
// Sorting so a unique set of IDs will always lead to the same group name.
// Then joining to create a string for `customKey`.
const group = [ ...player.get("neighborIDs"), player._id ].sort().join("-")
<Chat player={player} scope={game} customKey={group} />
```

Does this make sense?

**Comment by dapacica** [comment]
Yes this makes sense, but it doesn't really seem to solve my problem still. To be more specific, let's say we have 3 players in the game (let's call them player1, player2, and player3 for simplicity), and player1 is a neighbor to player2, player3 is a neighbor to player2, but player2 is a neighbor to both player1 and player3. This means that player1 and player2 can communicate back and forth as well as player2 and player3, but player3 should not be able to see player1's chat. So the problem is that player2 would have to have two different customKeys so that he can message player1 and player3 individually. Is there any way I can make it so player2 can send out a message to both player1 and player3 individually without making new chat windows?

**Comment by npaton** [comment]
I see. You want to show one chat window with multiple threads in it.

If I understood correctly this time, I think you should be able to "flag" messages as you create them and then filter which ones to display.

First, **on message creation**, you can add _arbitrary_ properties to messages. I put 2 different properties in this single example, both a group and specific neighbor IDs, you'd usually only need one, and of course you can use any variant on this pattern that suits your needs:

```jsx
<Chat
  player={player}
  scope={game}
  onNewMessage={(msg) => {
    msg.group = player.get("group");
    msg.onlyShowToPlayerIDs = player.get("neighborIDs");
    return msg;
  }}
/>
```

Then we can **filter** which messages to show with those custom properties. Again here I'm showing 2 examples at once, using a group and player IDs:

```jsx
<Chat
  player={player}
  scope={game}
  filter={(msgs) => msgs.filter((msg) => {
    return msg.group === player.get("group") ||
      msg.onlyShowToPlayerIDs.includes(player._id);
  })}
/>
```

I just wanted to show both parts individually, but you would use those 2 features in combination to produce the desired effect. With only the group example, that gives us:

```jsx
<Chat
  player={player}
  scope={game}
  onNewMessage={(msg) => {
    msg.group = player.get("group");
    return msg;
  }}
  filter={(msgs) => msgs.filter((msg) => msg.group === player.get("group"))}
/>
```

Let me know if that helps. ⛵

**Comment by dapacica** [comment]
Yup this helped a lot, I was able to tweak it a bit to fit the player data that I had stored and now it works perfectly. Thanks so much for the help!
